### ISSUE TITLE
cant run in windows

### ISSUE THREAD

**Issue by idhil23** [praveen-palanisamy/MemReFinder#2]
have you tried your production, before publishing

i have tried all your production for windows and nothing worked.

and similarly when self-producing, no pages are exposed. only shows the application in task manager windows

**Comment by praveen-palanisamy** [comment]
Hi @idhil23 ,
Yes. Here's a quick test with the Windows release: [MemReFinder-0.0.1.exe](https://github.com/praveen-palanisamy/MemReFinder/releases/download/v0.0.1/MemReFinder-0.0.1.exe):

https://github.com/praveen-palanisamy/MemReFinder/assets/4770482/08e7fa31-63d6-4aca-80ab-09773ce16a85

Could you describe your issue with details?

**Comment by idhil23** [comment]
nothing works. in my windows

![Screenshot_33](https://github.com/praveen-palanisamy/MemReFinder/assets/22818411/ee2b352e-87c5-450e-a6e5-7287c0eb4aa6)

**Comment by tronghieu60s** [comment]
> nothing works. in my windows
> 
> ![Screenshot_33](https://user-images.githubusercontent.com/22818411/249055125-ee2b352e-87c5-450e-a6e5-7287c0eb4aa6.jpg)

Open package.json and add extraFiles to build:
`"build": {
   ...
    "extraFiles": [
      "renderer/next.config.js"
    ],
    ...
    },`
