### ISSUE TITLE
How are you running auth on this?

### ISSUE THREAD

**Issue by willk1** [praveen-palanisamy/MemReFinder#5]
Hey question for you. Love your projects but how does auth function inside your application? This looks really cool and have been trying to figure out how to best implement auth with Electron while using nextjs. I guess how are you currently setting up and managing authentication on this? Any recs?

**Comment by praveen-palanisamy** [comment]
Hi @willk1,
Glad to hear. I am using [NextAuth.js](https://next-auth.js.org/) (and a PostgreSQL database via Supabase for persistence in this project/application). 
It is reasonably well integrated with Next.js and is easy to use with multiple options for auth credential providers (OAuth/OOpenID Connect), database backends and also supports JWTs for sessions.
You may find [these Tutorials and Explainers](https://next-auth.js.org/tutorials) useful. They include full walkthroughs and code examples.
